name: PR Check

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  gitleaks-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --repo-path=. --verbose
        env:
          GITLEAKS_ENABLE_COMMENTS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
